trigger:
- master

pr:
- master

pool:
  vmImage: 'windows-latest'
  
strategy:
  matrix:
    Config_Release:
        buildConfiguration: 'Release'
    Config_Debug:
        buildConfiguration: 'Debug'
        
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  displayName: Copy InferNull $(buildConfiguration)
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/InferNull/bin/$(buildConfiguration)'
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)/$(buildConfiguration)
  condition: succeeded()
  
- task: PublishPipelineArtifact@1
  displayName: Publish $(buildConfiguration)
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)/$(buildConfiguration)
    artifactName: InferNull - $(buildConfiguration) $(Build.BuildId)
